// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agl_debug.proto

#ifndef PROTOBUF_agl_5fdebug_2eproto__INCLUDED
#define PROTOBUF_agl_5fdebug_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "pose.pb.h"
#include "vector3d.pb.h"
#include "vector2d.pb.h"
#include "time.pb.h"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_agl_5fdebug_2eproto();
void protobuf_AssignDesc_agl_5fdebug_2eproto();
void protobuf_ShutdownFile_agl_5fdebug_2eproto();

class AglDebug;

// ===================================================================

class AglDebug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.AglDebug) */ {
 public:
  AglDebug();
  virtual ~AglDebug();

  AglDebug(const AglDebug& from);

  inline AglDebug& operator=(const AglDebug& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AglDebug& default_instance();

  void Swap(AglDebug* other);

  // implements Message ----------------------------------------------

  inline AglDebug* New() const { return New(NULL); }

  AglDebug* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AglDebug& from);
  void MergeFrom(const AglDebug& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AglDebug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double elapsed_time = 1;
  bool has_elapsed_time() const;
  void clear_elapsed_time();
  static const int kElapsedTimeFieldNumber = 1;
  double elapsed_time() const;
  void set_elapsed_time(double value);

  // required .gazebo.msgs.Pose vehicle_pose = 2;
  bool has_vehicle_pose() const;
  void clear_vehicle_pose();
  static const int kVehiclePoseFieldNumber = 2;
  const ::gazebo::msgs::Pose& vehicle_pose() const;
  ::gazebo::msgs::Pose* mutable_vehicle_pose();
  ::gazebo::msgs::Pose* release_vehicle_pose();
  void set_allocated_vehicle_pose(::gazebo::msgs::Pose* vehicle_pose);

  // required double current_agl = 3;
  bool has_current_agl() const;
  void clear_current_agl();
  static const int kCurrentAglFieldNumber = 3;
  double current_agl() const;
  void set_current_agl(double value);

  // required double average_agl = 4;
  bool has_average_agl() const;
  void clear_average_agl();
  static const int kAverageAglFieldNumber = 4;
  double average_agl() const;
  void set_average_agl(double value);

  // required .gazebo.msgs.Vector2d terrain_pts_sz = 5;
  bool has_terrain_pts_sz() const;
  void clear_terrain_pts_sz();
  static const int kTerrainPtsSzFieldNumber = 5;
  const ::gazebo::msgs::Vector2d& terrain_pts_sz() const;
  ::gazebo::msgs::Vector2d* mutable_terrain_pts_sz();
  ::gazebo::msgs::Vector2d* release_terrain_pts_sz();
  void set_allocated_terrain_pts_sz(::gazebo::msgs::Vector2d* terrain_pts_sz);

  // repeated .gazebo.msgs.Vector3d terrain_pts = 6;
  int terrain_pts_size() const;
  void clear_terrain_pts();
  static const int kTerrainPtsFieldNumber = 6;
  const ::gazebo::msgs::Vector3d& terrain_pts(int index) const;
  ::gazebo::msgs::Vector3d* mutable_terrain_pts(int index);
  ::gazebo::msgs::Vector3d* add_terrain_pts();
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >*
      mutable_terrain_pts();
  const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >&
      terrain_pts() const;

  // @@protoc_insertion_point(class_scope:gazebo.msgs.AglDebug)
 private:
  inline void set_has_elapsed_time();
  inline void clear_has_elapsed_time();
  inline void set_has_vehicle_pose();
  inline void clear_has_vehicle_pose();
  inline void set_has_current_agl();
  inline void clear_has_current_agl();
  inline void set_has_average_agl();
  inline void clear_has_average_agl();
  inline void set_has_terrain_pts_sz();
  inline void clear_has_terrain_pts_sz();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double elapsed_time_;
  ::gazebo::msgs::Pose* vehicle_pose_;
  double current_agl_;
  double average_agl_;
  ::gazebo::msgs::Vector2d* terrain_pts_sz_;
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d > terrain_pts_;
  friend void  protobuf_AddDesc_agl_5fdebug_2eproto();
  friend void protobuf_AssignDesc_agl_5fdebug_2eproto();
  friend void protobuf_ShutdownFile_agl_5fdebug_2eproto();

  void InitAsDefaultInstance();
  static AglDebug* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AglDebug

// required double elapsed_time = 1;
inline bool AglDebug::has_elapsed_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AglDebug::set_has_elapsed_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AglDebug::clear_has_elapsed_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AglDebug::clear_elapsed_time() {
  elapsed_time_ = 0;
  clear_has_elapsed_time();
}
inline double AglDebug::elapsed_time() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.elapsed_time)
  return elapsed_time_;
}
inline void AglDebug::set_elapsed_time(double value) {
  set_has_elapsed_time();
  elapsed_time_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.AglDebug.elapsed_time)
}

// required .gazebo.msgs.Pose vehicle_pose = 2;
inline bool AglDebug::has_vehicle_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AglDebug::set_has_vehicle_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AglDebug::clear_has_vehicle_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AglDebug::clear_vehicle_pose() {
  if (vehicle_pose_ != NULL) vehicle_pose_->::gazebo::msgs::Pose::Clear();
  clear_has_vehicle_pose();
}
inline const ::gazebo::msgs::Pose& AglDebug::vehicle_pose() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.vehicle_pose)
  return vehicle_pose_ != NULL ? *vehicle_pose_ : *default_instance_->vehicle_pose_;
}
inline ::gazebo::msgs::Pose* AglDebug::mutable_vehicle_pose() {
  set_has_vehicle_pose();
  if (vehicle_pose_ == NULL) {
    vehicle_pose_ = new ::gazebo::msgs::Pose;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.AglDebug.vehicle_pose)
  return vehicle_pose_;
}
inline ::gazebo::msgs::Pose* AglDebug::release_vehicle_pose() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.AglDebug.vehicle_pose)
  clear_has_vehicle_pose();
  ::gazebo::msgs::Pose* temp = vehicle_pose_;
  vehicle_pose_ = NULL;
  return temp;
}
inline void AglDebug::set_allocated_vehicle_pose(::gazebo::msgs::Pose* vehicle_pose) {
  delete vehicle_pose_;
  vehicle_pose_ = vehicle_pose;
  if (vehicle_pose) {
    set_has_vehicle_pose();
  } else {
    clear_has_vehicle_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.AglDebug.vehicle_pose)
}

// required double current_agl = 3;
inline bool AglDebug::has_current_agl() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AglDebug::set_has_current_agl() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AglDebug::clear_has_current_agl() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AglDebug::clear_current_agl() {
  current_agl_ = 0;
  clear_has_current_agl();
}
inline double AglDebug::current_agl() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.current_agl)
  return current_agl_;
}
inline void AglDebug::set_current_agl(double value) {
  set_has_current_agl();
  current_agl_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.AglDebug.current_agl)
}

// required double average_agl = 4;
inline bool AglDebug::has_average_agl() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AglDebug::set_has_average_agl() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AglDebug::clear_has_average_agl() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AglDebug::clear_average_agl() {
  average_agl_ = 0;
  clear_has_average_agl();
}
inline double AglDebug::average_agl() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.average_agl)
  return average_agl_;
}
inline void AglDebug::set_average_agl(double value) {
  set_has_average_agl();
  average_agl_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.AglDebug.average_agl)
}

// required .gazebo.msgs.Vector2d terrain_pts_sz = 5;
inline bool AglDebug::has_terrain_pts_sz() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AglDebug::set_has_terrain_pts_sz() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AglDebug::clear_has_terrain_pts_sz() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AglDebug::clear_terrain_pts_sz() {
  if (terrain_pts_sz_ != NULL) terrain_pts_sz_->::gazebo::msgs::Vector2d::Clear();
  clear_has_terrain_pts_sz();
}
inline const ::gazebo::msgs::Vector2d& AglDebug::terrain_pts_sz() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.terrain_pts_sz)
  return terrain_pts_sz_ != NULL ? *terrain_pts_sz_ : *default_instance_->terrain_pts_sz_;
}
inline ::gazebo::msgs::Vector2d* AglDebug::mutable_terrain_pts_sz() {
  set_has_terrain_pts_sz();
  if (terrain_pts_sz_ == NULL) {
    terrain_pts_sz_ = new ::gazebo::msgs::Vector2d;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.AglDebug.terrain_pts_sz)
  return terrain_pts_sz_;
}
inline ::gazebo::msgs::Vector2d* AglDebug::release_terrain_pts_sz() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.AglDebug.terrain_pts_sz)
  clear_has_terrain_pts_sz();
  ::gazebo::msgs::Vector2d* temp = terrain_pts_sz_;
  terrain_pts_sz_ = NULL;
  return temp;
}
inline void AglDebug::set_allocated_terrain_pts_sz(::gazebo::msgs::Vector2d* terrain_pts_sz) {
  delete terrain_pts_sz_;
  terrain_pts_sz_ = terrain_pts_sz;
  if (terrain_pts_sz) {
    set_has_terrain_pts_sz();
  } else {
    clear_has_terrain_pts_sz();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.AglDebug.terrain_pts_sz)
}

// repeated .gazebo.msgs.Vector3d terrain_pts = 6;
inline int AglDebug::terrain_pts_size() const {
  return terrain_pts_.size();
}
inline void AglDebug::clear_terrain_pts() {
  terrain_pts_.Clear();
}
inline const ::gazebo::msgs::Vector3d& AglDebug::terrain_pts(int index) const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.AglDebug.terrain_pts)
  return terrain_pts_.Get(index);
}
inline ::gazebo::msgs::Vector3d* AglDebug::mutable_terrain_pts(int index) {
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.AglDebug.terrain_pts)
  return terrain_pts_.Mutable(index);
}
inline ::gazebo::msgs::Vector3d* AglDebug::add_terrain_pts() {
  // @@protoc_insertion_point(field_add:gazebo.msgs.AglDebug.terrain_pts)
  return terrain_pts_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >*
AglDebug::mutable_terrain_pts() {
  // @@protoc_insertion_point(field_mutable_list:gazebo.msgs.AglDebug.terrain_pts)
  return &terrain_pts_;
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >&
AglDebug::terrain_pts() const {
  // @@protoc_insertion_point(field_list:gazebo.msgs.AglDebug.terrain_pts)
  return terrain_pts_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_agl_5fdebug_2eproto__INCLUDED
